version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3307:3306
  app:
    depends_on:
      - mysqldb
    build:
      context: .
      target: base
    command: sh -c "yarn mikro-orm schema:update --run&&nodemon src/main.ts -L"
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./src/:/app/src/
    ports:
      - $PORT:$PORT
    stdin_open: true
    environment:
      - DB_URL=$DB_URL
      - NODE_ENV=development
    tty: true
volumes: 
    db: